### ISSUE TITLE
Lat/Lon Viewbox order incorrect

### ISSUE THREAD

**Issue by wollac11** [f1ana/Nominatim.API#12]
Setting the viewbox for the forward geocoder doesn't seem to work correctly. Looking at the web requests on https://nominatim.openstreetmap.org it would appear that Nominatim expects a request of minLong, minLat, maxLong, maxLat whereas this library appears to send viewbox = minLat, minLong, maxLat, maxLong so the viewbox coordinates are inverted.

I would suggest that line 50 of ForwardGeocoder.cs should change from this:

`c.Add("viewbox", $"{v.minLatitude},{v.minLongitude},{v.maxLatitude},{v.maxLongitude}");`

to this:

`c.Add("viewbox", $"{v.minLongitude},{v.minLatitude},{v.maxLongitude},{v.maxLatitude}");`

**Comment by f1ana** [comment]
Hi @wollac11 - thanks for bringing this to my attention.  I'll make the change and push a new package over the weekend.  Thanks!

**Comment by f1ana** [comment]
This should be solved in aaf681ab3569441728d0487a860df5072d1aad4b.
Updated nuget package should be up shortly.  Thanks!

**Comment by wollac11** [comment]
Excellent, thanks!
