### ISSUE TITLE
GetRequest thread safety

### ISSUE THREAD

**Issue by Rickebo** [f1ana/Nominatim.API#14]
Performing the following in `GetRequest` is not thread safe since the headers of the static `HttpClient` changes between threads. 

https://github.com/f1ana/Nominatim.API/blob/f0e757f1c8c04836bb0a31d6f8efd9a7ab37169e/src/Nominatim.API/Web/WebInterface.cs#L27-L28

I suggest setting the header in a static constructor instead:
```
static WebInterface()
{
    _httpClient.DefaultRequestHeaders.UserAgent.Clear();
    _httpClient.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue("f1ana.Nominatim.API", Assembly.GetExecutingAssembly().GetName().Version.ToString()));
}
```

**Comment by f1ana** [comment]
Hi @Rickebo - do you have a fix in place that you would like to submit?

**Comment by Rickebo** [comment]
I cant submit a pull request at the moment but I fixed the issue in my fork of Nominatim.API in [this commit](https://github.com/Rickebo/Nominatim.API/commit/3e3590541f634a92109bcd744df99c1ee4827e1a).

**Comment by f1ana** [comment]
Hi @Rickebo - sorry for the delay, but I pushed a new package which should resolve this.  Could you confirm?

**Comment by Rickebo** [comment]
Looks like its fixed!
