### ISSUE TITLE
GeoJSON.Net version

### ISSUE THREAD

**Issue by ondrasvoboda** [f1ana/Nominatim.API#15]
Hi,
would it be possible to update GeoJSON.Net dependency to support GeoJSON.Net > 1.1.72?

I'm getting following error when version > 1.1.72:
`Could not load file or assembly 'GeoJSON.Net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

I believe it is caused by strong naming GeoJSON.Net starting with version 1.1.73. 

Thanks

**Comment by f1ana** [comment]
Hi @ondrasvoboda - I've updated GeoJSON to the latest version per your request and pushed a new package.  Could you confirm that your issue is resolved when you have a moment?

**Comment by ondrasvoboda** [comment]
Works fine, thanks @f1ana !
