### ISSUE TITLE
DotNetCore pull request

### ISSUE THREAD

**Issue by TheGuern** [f1ana/Nominatim.API#16]
Hi,
I am trying to submit a pull request for my DotNetCore branch, but it fails with Http 403. I am new to GitHub. Do you have to add me as a contributor, or something?
Description: Added .NetCore projects, removing dependency on Newtonsoft.Json
Paul

**Comment by f1ana** [comment]
Hi @TheGuern - you can fork my code and submit a pull request that way.

**Comment by TheGuern** [comment]
Hi Chris,
Thank you for pointing me to the Fork operation.  I am a seasoned developer, but new to git and GitHub.

I submitted a pull request, including your original projects (unchanged) and adding a .sln containing 2 new .net core 3.1 projects.

I have another project in progress. Let me know if this sounds like something you would like to add:

A .net core 3.1 worker service, easily published to Azure. Each geocoder provider would implement an IGeocoder interface, so the service can be configured to use either the GoogleMaps or Nominatim api. The worker service would:



  *   wake up every (configured interval) and execute a stored procedure which would return zero or one row of data needing to be geocoded. Something like:

SELECT TOP (1)
       [Id]
      ,[CompanyName]
      ,[Street]
      ,[City]
      ,[StateCode]
      ,[Zip]
  FROM  [SpatialData]
  WHERE
       ([Longitude] IS NULL OR [Latitude] IS NULL)
          AND [GeoCodeStatus] <> 'FAILED'
  ORDER BY  [GeoCodeUpdatedDate]


  *   [Latitude] and [Longitude] are computed columns, based on a [GeoLocation] AS [geography] column (Microsoft SQL Server);
  *   The [spatialData] table has an update trigger on any of the address columns which will invalidate (set to null) the [GeoLocation] column upon change; The above query will return nulls for [Latitude] and [Longitude] if [GeoLocation] Is null;
  *   Call the configured (google/nominatim) IGeocoder.Geocode(forwardGeoCodeRequest) method
  *   Execute a configured stored procedure name (like SpatialData_SetGeoLocation), passing in the new [Latitude] and [Longitude]


A Question you might ask: Why not just add an IGeoCoder to a web page, and call it from the UI whenever an address column is altered?
Answer: Because the free GeoCoding APIs have usage restrictions, like these:

  *   No heavy uses (an absolute maximum of 1 request per second)
(the service processes just the top (1) row at a time; in the case of bulk inserts or updates, the service's sleep interval enforces compliance with this rule).

  *   limit your requests to a single thread
  *   limited to 1 machine only, no distributed scripts (including multiple Amazon EC2 instances or similar)
  *   Results must be cached on your side. Clients sending repeatedly the same query may be classified as faulty and blocked.

My service attempts to address these restrictions.

Paul Guernsey
Guernsey55@outlook.com

**Comment by f1ana** [comment]
Closing because PR https://github.com/f1ana/Nominatim.API/pull/26 supersedes this effort.
