### ISSUE TITLE
Mage GeoJSON property protected to allow access

### ISSUE THREAD

**Issue by niels-heinemann** [f1ana/Nominatim.API#24]
Thanks for your great work. Could you please provide a package with

https://github.com/f1ana/Nominatim.API/blob/master/src/Nominatim.API/Models/GeocodeResponse.cs#L31

a non-private property?

Thanks a load

**Comment by f1ana** [comment]
I made this change and incorporated into this PR:  https://github.com/f1ana/Nominatim.API/pull/26
