### ISSUE TITLE
Are instances thread safe and can be configured as singletons?

### ISSUE THREAD

**Issue by ramonsmits** [f1ana/Nominatim.API#27]
Its not clear from the README is the code is threadsafe. How should these be registered for DI?

**Comment by f1ana** [comment]
The integration tests provide some guidance on how to register the services.
Scoped should be sufficient.  The way that we are using `IHttpClientFactory` _should_ be thread-safe, but unless you're making thousands of calls per second, it's probably not worth the trouble to use a singleton.
