### ISSUE TITLE
Getting 403 forbidden when testing forwardGeocoding, user-agent ?

### ISSUE THREAD

**Issue by taxx** [f1ana/Nominatim.API#6]
Tested the same url in browser and it works.
Then added a querystring in WebInterface.GetRequest as such:
`_httpClient.DefaultRequestHeaders.Add("User-Agent", "Mozilla/5.0 (Windows NT x.y; rv:10.0) Gecko/20100101 Firefox/10.0");`

And it works, however I don't know much about OSM/Nominatim yet and what the rules are.
(Are you supposed to register a UA with them beforehand?)
Or where it should be placed in your code :)

Also noted that the calls are made using http, works when the urls are changed from http to https.

**Comment by f1ana** [comment]
Hi @taxx - so, you are saying that changing the URLs from http to https resolve the issue without using a user-agent?

**Comment by f1ana** [comment]
I've got a fix out and I will push out a new package (v1.4.0) shortly.  Thanks!

**Comment by taxx** [comment]
Hello @f1ana , thanks for that!
Running the latest nuget package and getting responses now.
(Sorry about the confusion I caused related to http/https, it was a different thing. I see from the commit that you understood what I meant :))
