### ISSUE TITLE
Reverse Geocoder not working

### ISSUE THREAD

**Issue by Vrumfondel** [f1ana/Nominatim.API#8]
Always ends with an exception containing "400 (Bad Request)".

Even the test ends with this result ...

**Comment by Vrumfondel** [comment]
Just to be complete:
`Message: Test method Nominatim.API.Tests.GeocoderTests.TestSuccessfulReverseGeocode threw exception: 
System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 400 (Bad Request).) ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
`

**Comment by f1ana** [comment]
Thanks for letting me know.  Do you want to put together a PR to resolve?

**Comment by Vrumfondel** [comment]
Working on it.

**Comment by Vrumfondel** [comment]
Well; I don't have any write access to the repository, so how could I do a PR?

**Comment by f1ana** [comment]
You could fork the repo, do your work there, and then do a PR from yours to mine.
Alternatively, if you just put the patch in this issue, I can implement it when I get home.

**Comment by f1ana** [comment]
Closed with #9 and subsequent commits.
